x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: app

services:
  db:
    image: postgres:15
    restart: always
    environment:
      <<: *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      target: ${API_TARGET:-development}
    volumes:
      - ./api:/app
      - /app/.venv
    environment:
      POSTGRES_SERVER: db
      <<: *common-variables
      SECRET_KEY: your-secret-key-here
      ENVIRONMENT: ${ENVIRONMENT:-development}
      BACKEND_CORS_ORIGINS: '["http://localhost:3000"]'
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v1/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./ui
      target: ${UI_TARGET:-development}
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
