openapi: 3.1.0
info:
  title: DAHack AI
  version: 0.1.0
paths:
  /v1/healthz:
    get:
      tags:
      - health
      summary: Health Check
      description: Health check endpoint.
      operationId: health_check_v1_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/todos:
    post:
      tags:
      - todos
      summary: Create Todo
      operationId: create_todo_v1_todos_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - todos
      summary: List Todos
      description: List todos with optional filtering and pagination.
      operationId: list_todos_v1_todos_get
      parameters:
      - name: completed
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Completed
      - name: skip
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
          default: 0
          title: Skip
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
                title: Response List Todos V1 Todos Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/todos/{todo_id}:
    get:
      tags:
      - todos
      summary: Get Todo
      description: Get a todo by ID.
      operationId: get_todo_v1_todos__todo_id__get
      parameters:
      - name: todo_id
        in: path
        required: true
        schema:
          type: string
          title: Todo Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - todos
      summary: Update Todo
      description: Update a todo.
      operationId: update_todo_v1_todos__todo_id__patch
      parameters:
      - name: todo_id
        in: path
        required: true
        schema:
          type: string
          title: Todo Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - todos
      summary: Delete Todo
      description: Delete a todo.
      operationId: delete_todo_v1_todos__todo_id__delete
      parameters:
      - name: todo_id
        in: path
        required: true
        schema:
          type: string
          title: Todo Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Todo:
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          title: Title
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Due Date
        id:
          type: integer
          title: Id
        completed:
          type: boolean
          title: Completed
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          type: string
          format: date-time
          title: Updated At
      type: object
      required:
      - title
      - id
      - completed
      - created_at
      - updated_at
      title: Todo
      description: Schema for todo response.
    TodoCreate:
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          title: Title
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        due_date:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Due Date
      type: object
      required:
      - title
      title: TodoCreate
      description: Schema for creating a new todo.
    TodoUpdate:
      properties:
        title:
          anyOf:
          - type: string
            maxLength: 255
            minLength: 1
          - type: 'null'
          title: Title
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        completed:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Completed
        due_date:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Due Date
      type: object
      title: TodoUpdate
      description: Schema for updating a todo.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
